# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_id', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_count', models.IntegerField()),
                ('client_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='madadcore.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='SurplusDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_id', models.CharField(max_length=16, unique=True)),
                ('count', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus', to='madadcore.Drug')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_drug', to='madadcore.Hospital')),
            ],
        ),
        migrations.AddField(
            model_name='ordereddrug',
            name='surplus_drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='madadcore.SurplusDrug'),
        ),
        migrations.AlterUniqueTogether(
            name='surplusdrug',
            unique_together=set([('hospital', 'drug')]),
        ),
        migrations.AlterUniqueTogether(
            name='ordereddrug',
            unique_together=set([('client_hospital', 'surplus_drug')]),
        ),
    ]
