# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='mobile',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ordereddrug',
            name='safe_id',
            field=models.CharField(default=1, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ordereddrug',
            unique_together=set([]),
        ),
    ]
