# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadcore', '0002_auto_20170929_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
