# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models
from madadcore.helpers.csv_to_dict import csv_to_dict


class Migration(migrations.Migration):
    def load_drugs_data(apps, schema_editor):
        drug_model = apps.get_model("madadcore", "Drug")

        drug_model.objects.all().delete()
        all_drugs = csv_to_dict()
        for drug in all_drugs:
            drugobj = drug_model(safe_id=drug['safe_id'], name=drug['name'])
            try:
                drugobj.validate_unique()
            except Exception as e:
                print('duplicate safe_id {}'.format(drug['safe_id']))
            else:
                drugobj.save()

    dependencies = [
        ('madadcore', '0003_hospital_address'),
    ]

    operations = [
        migrations.RunPython(load_drugs_data, lambda apps, schema_editor: None)
    ]
