# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadcore', '0004_add_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereddrug',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'درحال بررسی'), (1, 'ارسال شده'), (2, 'دریافت شده')], default=0),
        ),
    ]
