# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadcore', '0005_ordereddrug_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusdrug',
            name='current_count',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='surplusdrug',
            name='initial_count',
            field=models.FloatField(default=0),
        ),
    ]
