# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadcore', '0007_remove_surplusdrug_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surplusdrug',
            name='current_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surplusdrug',
            name='initial_count',
            field=models.IntegerField(default=0),
        ),
    ]
