# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('madadcore', '0008_auto_20171027_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereddrug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereddrug',
            name='delivered_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordereddrug',
            name='sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='surplusdrug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
