# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadcore', '0010_auto_20180228_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusdrug',
            name='cat',
            field=models.SmallIntegerField(choices=[(0, 'سایر'), (1, 'دارو'), (2, 'لوازم')], default=0),
        ),
        migrations.AddField(
            model_name='surplusdrug',
            name='drug_type',
            field=models.SmallIntegerField(choices=[(0, 'سایر'), (1, 'راکد'), (2, 'مازاد')], default=0),
        ),
        migrations.AddField(
            model_name='surplusdrug',
            name='price',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordereddrug',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'درحال بررسی'), (1, 'ارسال شده'), (2, 'دریافت شده'), (3, 'لغو شده')], default=0),
        ),
    ]
